-- 1. Listar todas las ciudades registradas
SELECT * FROM CIUDAD;

-- 2. Mostrar todos los clientes junto con el nombre de su ciudad
SELECT C.ID_CLIENTE, C.NOMBRE_CLIENTE, CD.NOMBRE_CIUDAD
FROM CLIENTE C
JOIN CIUDAD CD ON C.ID_CIUDAD = CD.ID_CIUDAD;

-- 3. Obtener todas las facturas emitidas, con cliente y local asociados
SELECT F.ID_FACTURA, CL.NOMBRE_CLIENTE, L.NOMBRE_LOCAL, F.FECHA, F.TOTAL_FACTURA
FROM FACTURA F
JOIN CLIENTE CL ON F.ID_CLIENTE = CL.ID_CLIENTE
JOIN LOCAL L ON F.ID_LOCAL = L.ID_LOCAL;

-- 4. Ver los productos vendidos en la factura 1003
SELECT DF.ID_DETALLE, P.NOMBRE_PRODUCTO, DF.CANTIDAD, DF.PRECIO_UNITARIO, DF.TOTAL
FROM DETALLE_FACTURA DF
JOIN PRODUCTO P ON DF.ID_PRODUCTO = P.ID_PRODUCTO
WHERE DF.ID_FACTURA = 1003;

-- 5. Consultar todas las facturas que incluyen servicios
SELECT F.ID_FACTURA, S.NOMBRE_SERVICIO, DF.CANTIDAD, DF.TOTAL
FROM DETALLE_FACTURA DF
JOIN SERVICIO S ON DF.ID_SERVICIO = S.ID_SERVICIO
JOIN FACTURA F ON DF.ID_FACTURA = F.ID_FACTURA;

-- 6. Mostrar los comentarios asociados a una factura específica
SELECT * FROM COMENTARIO WHERE ID_FACTURA = 1001;
