-- 1. Listar todas las ciudades registradas
SELECT * FROM CIUDAD;

-- 2. Mostrar todos los clientes con su ciudad y teléfono
SELECT CL.ID_CLIENTE, CL.NOMBRE_CLIENTE, C.NOMBRE_CIUDAD, CL.TELEFONO_CLIENTE
FROM CLIENTE CL
JOIN CIUDAD C ON CL.ID_CIUDAD = C.ID_CIUDAD;

-- 3. Obtener resumen de facturas emitidas con total acumulado por cliente
SELECT CL.ID_CLIENTE, CL.NOMBRE_CLIENTE, COUNT(F.ID_FACTURA) AS TOTAL_FACTURAS, SUM(F.TOTAL_FACTURA) AS MONTO_TOTAL
FROM CLIENTE CL
JOIN FACTURA F ON CL.ID_CLIENTE = F.ID_CLIENTE
GROUP BY CL.ID_CLIENTE, CL.NOMBRE_CLIENTE;

-- 4. Listar productos vendidos en facturas junto con nombre de cliente y fecha
SELECT DF.ID_DETALLE, P.NOMBRE_PRODUCTO, DF.CANTIDAD, DF.TOTAL, F.FECHA, C.NOMBRE_CLIENTE
FROM DETALLE_FACTURA DF
JOIN PRODUCTO P ON DF.ID_PRODUCTO = P.ID_PRODUCTO
JOIN FACTURA F ON DF.ID_FACTURA = F.ID_FACTURA
JOIN CLIENTE C ON F.ID_CLIENTE = C.ID_CLIENTE;

-- 5. Listar servicios prestados, indicando cuántas veces se ha facturado cada uno
SELECT S.NOMBRE_SERVICIO, COUNT(DF.ID_DETALLE) AS VECES_VENDIDO
FROM DETALLE_FACTURA DF
JOIN SERVICIO S ON DF.ID_SERVICIO = S.ID_SERVICIO
GROUP BY S.NOMBRE_SERVICIO;

-- 6. Consultar el total facturado por ciudad
SELECT CD.NOMBRE_CIUDAD, SUM(F.TOTAL_FACTURA) AS TOTAL_FACTURADO
FROM FACTURA F
JOIN CLIENTE CL ON F.ID_CLIENTE = CL.ID_CLIENTE
JOIN CIUDAD CD ON CL.ID_CIUDAD = CD.ID_CIUDAD
GROUP BY CD.NOMBRE_CIUDAD;

-- 7. Obtener detalle completo de una factura (productos/servicios y totales)
SELECT F.ID_FACTURA, DF.ID_DETALLE, P.NOMBRE_PRODUCTO, S.NOMBRE_SERVICIO,
       DF.CANTIDAD, DF.PRECIO_UNITARIO, DF.TOTAL
FROM FACTURA F
LEFT JOIN DETALLE_FACTURA DF ON F.ID_FACTURA = DF.ID_FACTURA
LEFT JOIN PRODUCTO P ON DF.ID_PRODUCTO = P.ID_PRODUCTO
LEFT JOIN SERVICIO S ON DF.ID_SERVICIO = S.ID_SERVICIO
WHERE F.ID_FACTURA = 1003;

-- 8. Buscar facturas con comentarios críticos (que contengan la palabra 'recomienda' o 'garantía')
SELECT CM.ID_FACTURA, CM.TEXTO
FROM COMENTARIO CM
WHERE LOWER(CM.TEXTO) LIKE '%recomienda%' OR LOWER(CM.TEXTO) LIKE '%garantía%';

