-- ===========================
-- ANEXO 1: CREACIÓN DE TABLAS
-- ===========================

CREATE TABLE CIUDAD (
   ID_CIUDAD            VARCHAR(6) NOT NULL,
   NOMBRE_CIUDAD        VARCHAR(50),
   ESTADO               VARCHAR(50),
   CODIGO_POSTAL        NUMERIC(15,0),
   PRIMARY KEY (ID_CIUDAD)
);

CREATE TABLE CLIENTE (
   ID_CLIENTE           VARCHAR(6) NOT NULL,
   ID_CIUDAD            VARCHAR(6) NOT NULL,
   NOMBRE_CLIENTE       VARCHAR(100),
   NOMBRE_COMPANIA      VARCHAR(100),
   DIRECCION_CLIENTE    VARCHAR(200),
   TELEFONO_CLIENTE     NUMERIC(20,0),
   PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE COMENTARIO (
   ID_COMENTARIO        VARCHAR(6) NOT NULL,
   ID_FACTURA           NUMERIC(6,0) NOT NULL,
   TEXTO                VARCHAR(2000),
   PRIMARY KEY (ID_COMENTARIO)
);

CREATE TABLE DETALLE_FACTURA (
   ID_DETALLE           VARCHAR(6) NOT NULL,
   ID_FACTURA           NUMERIC(6,0) NOT NULL,
   ID_SERVICIO          VARCHAR(6),
   ID_PRODUCTO          VARCHAR(6),
   CANTIDAD             NUMERIC(5,0),
   PRECIO_UNITARIO      NUMERIC(15,0),
   TOTAL                NUMERIC(30,0),
   PRIMARY KEY (ID_DETALLE)
);

CREATE TABLE FACTURA (
   ID_FACTURA           NUMERIC(6,0) NOT NULL,
   ID_CLIENTE           VARCHAR(6) NOT NULL,
   ID_LOCAL             VARCHAR(6) NOT NULL,
   FECHA                DATE,
   SUBTOTAL             NUMERIC(15,0),
   IMPUESTO             FLOAT(6),
   TOTAL_FACTURA        NUMERIC(30,0),
   PRIMARY KEY (ID_FACTURA)
);

CREATE TABLE LOCAL (
   ID_LOCAL             VARCHAR(6) NOT NULL,
   ID_CIUDAD            VARCHAR(6) NOT NULL,
   NOMBRE_LOCAL         VARCHAR(100),
   DIRECCION_LOCAL      VARCHAR(200),
   TELEFONO_LOCAL       NUMERIC(20,0),
   PRIMARY KEY (ID_LOCAL)
);

CREATE TABLE PRODUCTO (
   ID_PRODUCTO          VARCHAR(6) NOT NULL,
   NOMBRE_PRODUCTO      VARCHAR(100),
   DESCRIPCION_PRODUCTO VARCHAR(1000),
   PRECIO_PRODUCTO      NUMERIC(15,0),
   PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE SERVICIO (
   ID_SERVICIO          VARCHAR(6) NOT NULL,
   NOMBRE_SERVICIO      VARCHAR(100),
   DESCRIPCION_SERVICIO VARCHAR(1000),
   PRECIO_SERVICIO      NUMERIC(15,0),
   PRIMARY KEY (ID_SERVICIO)
);

-- ===========================
-- RELACIONES Y RESTRICCIONES
-- ===========================

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_RESIDE_CIUDAD FOREIGN KEY (ID_CIUDAD)
      REFERENCES CIUDAD (ID_CIUDAD) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENTAR_GUARDA_FACTURA FOREIGN KEY (ID_FACTURA)
      REFERENCES FACTURA (ID_FACTURA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_DETALLE__CONTIENE_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
      REFERENCES PRODUCTO (ID_PRODUCTO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_DETALLE__DESCRIBE_SERVICIO FOREIGN KEY (ID_SERVICIO)
      REFERENCES SERVICIO (ID_SERVICIO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_DETALLE__INCLUYE_FACTURA FOREIGN KEY (ID_FACTURA)
      REFERENCES FACTURA (ID_FACTURA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE FACTURA ADD CONSTRAINT FK_FACTURA_EMITE_LOCAL FOREIGN KEY (ID_LOCAL)
      REFERENCES LOCAL (ID_LOCAL) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE FACTURA ADD CONSTRAINT FK_FACTURA_PERTENECE_CLIENTE FOREIGN KEY (ID_CLIENTE)
      REFERENCES CLIENTE (ID_CLIENTE) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE LOCAL ADD CONSTRAINT FK_LOCAL_OPERA_CIUDAD FOREIGN KEY (ID_CIUDAD)
      REFERENCES CIUDAD (ID_CIUDAD) ON DELETE RESTRICT ON UPDATE RESTRICT;
